# Generated by Django 4.1 on 2022-08-24 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField(default=0)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('lastdate', models.DateField()),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('job_description', models.TextField()),
                ('cmp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
