# Generated by Django 4.1 on 2022-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cat',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=100, null=True),
        ),
    ]
