# Generated by Django 4.1 on 2022-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cat',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five')], max_length=100, null=True),
        ),
    ]
