# Generated by Django 4.1 on 2022-09-13 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_image_alter_user_cat_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliedjob',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('can_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
    ]
