# Generated by Django 4.1 on 2022-09-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_appliedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='job_id',
            new_name='jobs_id',
        ),
    ]
