# Generated by Django 4.1 on 2022-09-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_job_id_appliedjob_jobs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='jobs_id',
        ),
    ]
