# Generated by Django 4.1 on 2022-09-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_appliedjob_jobs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='jobs_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.job'),
        ),
    ]
