# Generated by Django 4.1 on 2022-09-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recruiter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
