# Generated by Django 4.1 on 2022-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
