# Generated by Django 4.1 on 2022-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='accept'),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='reject',
            field=models.BooleanField(default=True, verbose_name='reject'),
        ),
    ]
