# Generated by Django 4.1 on 2022-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_appliedjob_accept_appliedjob_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
