# Generated by Django 4.1 on 2022-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='applied',
            field=models.BooleanField(default=True, verbose_name='applied'),
        ),
    ]
