# Generated by Django 4.1 on 2022-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_appliedjob_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proof',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
