# Generated by Django 4.1 on 2022-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_user_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='approved'),
        ),
    ]
