# Generated by Django 4.1 on 2022-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_user_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
