# Generated by Django 4.1 on 2022-09-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_user_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
    ]
