# Generated by Django 4.1 on 2022-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_image_alter_user_phone_alter_user_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('blogs', models.TextField(null=True)),
            ],
        ),
    ]
