# Generated by Django 4.1 on 2022-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_feedback_bad_feedback_good_alter_user_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='neutral',
            field=models.BooleanField(default=True, verbose_name='neutral'),
        ),
    ]
