# Generated by Django 4.1 on 2022-12-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_feedback_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('categ_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('categname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
