# Generated by Django 4.1 on 2022-12-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
