# Generated by Django 4.1 on 2022-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_categ_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
