# Generated by Django 4.1 on 2022-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='professsion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
