# Generated by Django 4.1 on 2022-12-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_blog_pp_blog_professsion'),
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('intern_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('title', models.CharField(max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('enddate', models.DateField()),
                ('caption', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
