# Generated by Django 4.1 on 2022-12-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_internship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='duration',
            new_name='durno',
        ),
        migrations.AddField(
            model_name='internship',
            name='durex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
