# Generated by Django 4.1 on 2022-12-21 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_duration_internship_durno_internship_durex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interndate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='interntimes',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
