# Generated by Django 4.1 on 2022-12-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_user_interndate_user_interntimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interndate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interntimes',
        ),
    ]
