# Generated by Django 4.1 on 2022-12-22 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_user_interndate_remove_user_interntimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='classdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('interndate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('interntimes', models.CharField(default=0, max_length=100, null=True)),
                ('candi_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.internship')),
            ],
        ),
    ]
