# Generated by Django 4.1 on 2022-12-30 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_classdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('type', models.CharField(max_length=100, null=True)),
                ('train_date', models.DateField()),
                ('train_time', models.CharField(default=0, max_length=100, null=True)),
                ('can_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
