# Generated by Django 4.1 on 2023-01-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desti',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
