# Generated by Django 4.1 on 2023-01-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='resdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('carobj', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('plus', models.CharField(blank=True, max_length=100)),
                ('ten', models.CharField(blank=True, max_length=100)),
                ('projects', models.TextField(blank=True)),
                ('certi', models.TextField(blank=True)),
                ('achi', models.TextField(blank=True)),
                ('interns', models.TextField(blank=True)),
                ('refe', models.TextField(blank=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True)),
                ('strength', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('hob', models.TextField(blank=True, null=True)),
                ('soci', models.CharField(blank=True, max_length=100)),
                ('coun', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=0, verbose_name='status')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default=0, max_length=100, null=True)),
            ],
        ),
    ]
