# Generated by Django 4.1 on 2023-01-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_resdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='resdetails',
            name='res_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
