# Generated by Django 4.1 on 2023-01-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_resdetails_id_resdetails_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resdetails',
            name='res_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
