# Generated by Django 4.1 on 2023-01-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_resdetails_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resdetails',
            name='gender',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
