# Generated by Django 4.1 on 2023-01-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_resdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resdetails',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
