# Generated by Django 4.1 on 2023-01-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_resdetails_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resdetails',
            new_name='res',
        ),
    ]
