# Generated by Django 4.1 on 2023-01-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_resdetails_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='ress',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('carobj', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('plus', models.CharField(blank=True, max_length=100)),
                ('ten', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='res',
        ),
    ]
