# Generated by Django 4.1 on 2023-01-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_ress_delete_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='type',
            new_name='typ',
        ),
    ]
