# Generated by Django 4.1 on 2023-01-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_resumm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resumm',
        ),
    ]
