# Generated by Django 4.1 on 2023-01-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_resumme'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduling',
            fields=[
                ('sche_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('typp', models.CharField(max_length=100, null=True)),
                ('train_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
