# Generated by Django 4.1 on 2023-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_delete_ress_scheduling_can_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='dura',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
