# Generated by Django 4.1 on 2023-01-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_score_delete_ress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
