# Generated by Django 4.1 on 2023-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_delete_ress_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='acc',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='dec',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
