# Generated by Django 4.1 on 2023-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_delete_ress_scheduling_acc_scheduling_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
