# Generated by Django 4.1 on 2023-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_delete_ress_scheduling_reason'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='scheduling',
            name='can_date',
            field=models.DateTimeField(null=True),
        ),
    ]
