# Generated by Django 4.1 on 2023-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_delete_ress_alter_scheduling_can_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='can_date',
            field=models.DateTimeField(null=True),
        ),
    ]
