# Generated by Django 4.1 on 2023-02-06 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_delete_ress_alter_scheduling_can_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedul',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('typee', models.CharField(max_length=100, null=True)),
                ('dur', models.CharField(max_length=100, null=True)),
                ('train_dat', models.DateTimeField()),
                ('acep', models.BooleanField(default=False, verbose_name='status')),
                ('decli', models.BooleanField(default=True, verbose_name='status')),
                ('reas', models.TextField(blank=True, null=True)),
                ('can_dat', models.DateTimeField(default=0, null=True)),
                ('can_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.training')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
