# Generated by Django 4.1 on 2023-02-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_schedul_delete_ress_alter_scheduling_can_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='can_date',
            field=models.DateTimeField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='schedul',
        ),
    ]
