# Generated by Django 4.1 on 2023-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_delete_ress_alter_scheduling_can_date_delete_schedul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='can_date',
            field=models.DateTimeField(null=True),
        ),
    ]
