# Generated by Django 4.1 on 2023-02-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_delete_ress_alter_scheduling_can_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='can_id',
            new_name='com_id',
        ),
    ]
