# Generated by Django 4.1 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_delete_ress_rename_can_id_scheduling_com_id'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='scheduling',
            name='approvedd',
            field=models.BooleanField(default=False, verbose_name='approveds'),
        ),
    ]
