# Generated by Django 4.1 on 2023-02-10 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_delete_ress_scheduling_approvedd'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('cann_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comm_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
    ]
