# Generated by Django 4.1 on 2023-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_offer_delete_ress'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='offer',
            name='cann_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
