# Generated by Django 4.1 on 2023-02-10 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_delete_ress_alter_offer_cann_id_alter_offer_comm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerr',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('comm_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
    ]
