# Generated by Django 4.1 on 2023-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_offerr_delete_ress'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
