# Generated by Django 4.1 on 2023-02-15 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_delete_ress_internship_category'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='resumme',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
