# Generated by Django 4.1 on 2023-02-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_delete_ress_resumme_user_id'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='resumme',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
