# Generated by Django 4.1 on 2023-02-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_delete_ress_alter_resumme_user_id'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
