# Generated by Django 4.1 on 2023-02-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_delete_ress_job_jobtype_job_qualification'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='internship',
            name='certificate',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='moreinfo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='onoff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='openings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='whoapply',
            field=models.TextField(null=True),
        ),
    ]
