# Generated by Django 4.1 on 2023-02-17 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_delete_ress_internship_certificate_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='internship',
            name='openings',
        ),
    ]
