# Generated by Django 4.1 on 2023-02-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_delete_ress_internship_tim'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='user',
            name='siteurl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
