# Generated by Django 4.1 on 2023-03-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_rating_delete_ress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
