# Generated by Django 4.1 on 2023-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_remove_rating_user_delete_ress_delete_rating'),
    ]

    operations = [

        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
