# Generated by Django 4.1 on 2023-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_delete_ress_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wi_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkk', models.BooleanField(default=True, verbose_name='checkk')),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('comm_id', models.IntegerField(blank=True, null=True)),
                ('jobb_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        
    ]
