# Generated by Django 4.1 on 2023-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_wishlist_delete_ress'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='wishlist',
            name='checkk',
            field=models.BooleanField(default=False, verbose_name='checkk'),
        ),
    ]
