# Generated by Django 4.1 on 2023-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_delete_ress_alter_wishlist_checkk'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='job',
            name='cper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='plper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='startdate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='job',
            name='tper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
