# Generated by Django 4.1 on 2023-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_delete_ress_job_cper_job_plper_job_startdate_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='job',
            name='experiencein',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
