# Generated by Django 4.1 on 2023-03-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_delete_ress_job_experiencein'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='job',
            name='expl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
