# Generated by Django 4.1 on 2023-03-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_delete_ress_job_expl'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='internship',
            name='stdate',
            field=models.DateField(),
        ),
    ]
