# Generated by Django 4.1 on 2023-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_delete_ress_internship_stdate'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
