# Generated by Django 4.1 on 2023-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_delete_ress_alter_job_experience'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='resumme',
            name='colcourse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumme',
            name='colpy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumme',
            name='plusmarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumme',
            name='pluspy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumme',
            name='schomarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumme',
            name='schopy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
