# Generated by Django 4.1 on 2023-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_delete_ress_resumme_colcourse_resumme_colpy_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='resumme',
            name='refe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
