# Generated by Django 4.1 on 2023-03-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_delete_ress_alter_resumme_refe'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('comp_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
       
    ]
