# Generated by Django 4.1 on 2023-03-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_payment_delete_ress'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='payment',
            name='comp_id',
        ),
    ]
