# Generated by Django 4.1 on 2023-03-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_delete_ress_remove_payment_comp_id'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
    ]
