# Generated by Django 4.1 on 2023-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_delete_ress_payment_paid'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
