# Generated by Django 4.1 on 2023-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_delete_ress_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='interdetails',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
            ],
        ),
       
    ]
