# Generated by Django 4.1 on 2023-04-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_interdetails_delete_ress'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='interdetails',
            name='paid',
        ),
        migrations.AddField(
            model_name='interdetails',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
