# Generated by Django 4.1 on 2023-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_delete_ress_remove_interdetails_paid_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='interdetails',
            name='interns',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
