# Generated by Django 4.1 on 2023-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_delete_ress_interdetails_interns'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='interdetails',
            name='interns1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
