# Generated by Django 4.1 on 2023-04-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_delete_ress_interdetails_interns1'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='interdetails',
            name='interns1',
        ),
    ]
