# Generated by Django 4.1 on 2023-04-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_delete_ress_remove_interdetails_interns1'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='resumme',
            name='achi',
        ),
        migrations.RemoveField(
            model_name='resumme',
            name='certi',
        ),
        migrations.RemoveField(
            model_name='resumme',
            name='interns',
        ),
        migrations.RemoveField(
            model_name='resumme',
            name='projects',
        ),
    ]
