# Generated by Django 4.1 on 2023-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_delete_ress_remove_resumme_achi_remove_resumme_certi_and_more'),
    ]

    operations = [
       
        migrations.RenameField(
            model_name='interdetails',
            old_name='pay_id',
            new_name='in_id',
        ),
        migrations.AddField(
            model_name='interdetails',
            name='interndate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='interdetails',
            name='internname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
