# Generated by Django 4.1 on 2023-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_delete_ress_rename_pay_id_interdetails_in_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='achidetails',
            fields=[
                ('achi_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('achiname', models.CharField(max_length=100, null=True)),
                ('achiinfo', models.CharField(max_length=100, null=True)),
                ('achidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='certidetails',
            fields=[
                ('cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('certiname', models.CharField(max_length=100, null=True)),
                ('cerinfo', models.CharField(max_length=100, null=True)),
                ('certidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='projectdetails',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('proname', models.CharField(max_length=100, null=True)),
                ('prodetails', models.CharField(max_length=100, null=True)),
            ],
        ),
       
    ]
