# Generated by Django 4.1 on 2023-04-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_achidetails_certidetails_projectdetails_delete_ress'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='scheduling',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
